name: Install on OSX
on:
  push:
  pull_request:
jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Make GHC 9.8 the default
        run:
          echo "/opt/homebrew/Cellar/ghc@9.8/9.8.2/bin" >> $GITHUB_PATH
      - name: Install copilot
        run: |
          ls
          pwd
          brew update
          brew install -v --build-from-source copilot.rb
      - name: Confirm that it runs
        run: |
          ghci -package-env /opt/homebrew/Cellar/copilot/4.0_1/lib/packages.env <<< 'import Language.Copilot; main = putStrLn "Success"'
